// src/constants/usStatesForZips.js
export const ZIP_STATE_FILES = [
  { abbr: 'ak', name: 'alaska' },
  { abbr: 'al', name: 'alabama' },
  { abbr: 'ar', name: 'arkansas' },
  { abbr: 'az', name: 'arizona' },
  { abbr: 'ca', name: 'california' },
  { abbr: 'co', name: 'colorado' },
  { abbr: 'ct', name: 'connecticut' },
  { abbr: 'dc', name: 'district of columbia' },
  { abbr: 'de', name: 'delaware' },
  { abbr: 'fl', name: 'florida' },
  { abbr: 'ga', name: 'georgia' },
  { abbr: 'hi', name: 'hawaii' },
  { abbr: 'ia', name: 'iowa' },
  { abbr: 'id', name: 'idaho' },
  { abbr: 'il', name: 'illinois' },
  { abbr: 'in', name: 'indiana' },
  { abbr: 'ks', name: 'kansas' },
  { abbr: 'ky', name: 'kentucky' },
  { abbr: 'la', name: 'louisiana' },
  { abbr: 'ma', name: 'massachusetts' },
  { abbr: 'md', name: 'maryland' },
  { abbr: 'me', name: 'maine' },
  { abbr: 'mi', name: 'michigan' },
  { abbr: 'mn', name: 'minnesota' },
  { abbr: 'mo', name: 'missouri' },
  { abbr: 'ms', name: 'mississippi' },
  { abbr: 'mt', name: 'montana' },
  { abbr: 'nc', name: 'north carolina' },
  { abbr: 'nd', name: 'north dakota' },
  { abbr: 'ne', name: 'nebraska' },
  { abbr: 'nh', name: 'new hampshire' },
  { abbr: 'nj', name: 'new jersey' },
  { abbr: 'nm', name: 'new mexico' },
  { abbr: 'nv', name: 'nevada' },
  { abbr: 'ny', name: 'new york' },
  { abbr: 'oh', name: 'ohio' },
  { abbr: 'ok', name: 'oklahoma' },
  { abbr: 'or', name: 'oregon' },
  { abbr: 'pa', name: 'pennsylvania' },
  { abbr: 'ri', name: 'rhode island' },
  { abbr: 'sc', name: 'south carolina' },
  { abbr: 'sd', name: 'south dakota' },
  { abbr: 'tn', name: 'tennessee' },
  { abbr: 'tx', name: 'texas' },
  { abbr: 'ut', name: 'utah' },
  { abbr: 'va', name: 'virginia' },
  { abbr: 'vt', name: 'vermont' },
  { abbr: 'wa', name: 'washington' },
  { abbr: 'wi', name: 'wisconsin' },
  { abbr: 'wv', name: 'west virginia' },
  { abbr: 'wy', name: 'wyoming' },
];